services:
  wordpress-db:
    image: mariadb:latest
    container_name: casosex-wordpress-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: wordpress_root_pass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_pass
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.10'
          memory: 64M
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: casosex-wordpress
    restart: unless-stopped
    ports:
      - "8085:80"
    environment:
      WORDPRESS_DB_HOST: wordpress-db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_pass
      WORDPRESS_DB_NAME: wordpress
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 128M
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - wordpress-db

volumes:
  db_data:
  wp_data:
