FROM node:22-alpine

WORKDIR /app

# Instala pacotes mínimos do Alpine
RUN apk add --no-cache git curl
RUN npm install -g pnpm

COPY package*.json pnpm-workspace.yaml ./
COPY self-essentials ./self-essentials

# Instala dependências do monorepo
RUN pnpm install --no-frozen-lockfile

COPY . .

EXPOSE 4321

CMD ["pnpm", "dev"]

