FROM node:22-slim

WORKDIR /app

# Instala glibc e utilitários
RUN apt-get update && apt-get install -y --no-install-recommends curl libc6 && rm -rf /var/lib/apt/lists/*

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 4321

# Garante que as dependências binárias fiquem prontas
CMD ["npm", "run", "dev"]
