name = "volupia-cockpit"
main = "worker/index.ts"
compatibility_date = "2026-08-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "volupia-db"
database_id = "a7e5672c-8eb6-4871-a60b-17541e2da457"
migrations_dir = "migrations"

[vars]
ENVIRONMENT = "production"
