name = "volupia-cockpit"
main = "worker/index.ts"
compatibility_date = "2026-08-25"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "usevolupia.com.br/*", zone_name = "usevolupia.com.br" },
  { pattern = "*.usevolupia.com.br/*", zone_name = "usevolupia.com.br" }
]

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = true
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "volupia-db"
database_id = "a7e5672c-8eb6-4871-a60b-17541e2da457"
migrations_dir = "migrations"

[vars]
ENVIRONMENT = "production"
GOOGLE_CLIENT_ID = "1024367308872-i1uo09sq0naqqcq1b8sk34prefqf55s6.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
GOOGLE_REDIRECT_URI = "https://app.usevolupia.com.br/api/auth/google/callback"
