name = "volupia-cockpit"
main = "worker/index.ts"
compatibility_date = "2026-08-25"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "app.usevolupia.com.br/*", zone_name = "usevolupia.com.br" },
  { pattern = "usevolupia.com.br/*", zone_name = "usevolupia.com.br" },
  { pattern = "www.usevolupia.com.br/*", zone_name = "usevolupia.com.br" }
]

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "volupia-db"
database_id = "a7e5672c-8eb6-4871-a60b-17541e2da457"
migrations_dir = "migrations"

[vars]
ENVIRONMENT = "production"
