<?php
namespace Whols_Pro\Vue_Settings;

class Settings_Schema {
    /**
     * Get the complete settings schema
     */
    public static function get_schema() {
        return array_merge(
            // General
            require __DIR__ . '/schema-parts/general.php',

            // Registration
            require __DIR__ . '/schema-parts/registration.php',

            // Fields Manager
            require __DIR__ . '/schema-parts/fields-manager.php',

            // Product Visibility
            require __DIR__ . '/schema-parts/product-visibility.php',

            // Wholesale only categories
            require __DIR__ . '/schema-parts/wholesale-only-categories.php',

            // Guest Access
            require __DIR__ . '/schema-parts/guest-access.php',

            // Dynamic Rules
            require __DIR__ . '/schema-parts/dynamic-rules.php',

            // Request a Quote
            require __DIR__ . '/schema-parts/request-a-quote.php',

            // Conversation
            require __DIR__ . '/schema-parts/conversation.php',

            // Wallet
            require __DIR__ . '/schema-parts/wallet.php',

            // Save Order List
            require __DIR__ . '/schema-parts/save-order-list.php',

            // Email Notifications
            require __DIR__ . '/schema-parts/email-notifications.php',

            // Custom Thank You Message
            require __DIR__ . '/schema-parts/custom-thank-you-message.php',

            // Others
            require __DIR__ . '/schema-parts/others.php',

            // Design
            require __DIR__ . '/schema-parts/design.php',

            // Bulk Order Form
            require __DIR__ . '/schema-parts/bulk-order-form.php',
        );
    }

    /**
     * Get settings schema as JavaScript
     */
    public static function get_js_schema() {
        $schema = self::get_schema();

        // Convert to JavaScript
        $js = "// Auto-generated from PHP Settings_Schema class\n";
        $js .= "// Do not edit this file directly\n\n";
        $js .= "export const settingsSchema = " . json_encode($schema, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) . ";\n\n";

        return $js;
    }

    /**
     * Generate JavaScript schema file
     */
    public static function generate_js_schema() {
        $js_file = dirname(dirname(dirname(__FILE__))) . '/src/vue-settings/config/settings-schema.js';
        file_put_contents($js_file, self::get_js_schema());
    }
}