#!/usr/bin/env python3
"""
Sovereign Extractor: Mercado Pago Mobile AppShell DNA Tokens
Scans decompiled APK resources and synthesizes mobile-app-first design tokens into YAML and JSON.
"""

import os
import json
import re
import glob
from pathlib import Path

MP_RES_DIR = "/media/jeffer/5aab5a95-8290-d3f7-2e4f-8c27cc2d09a93/adsentice/self-iinspirations/com.mercadopago.wallet_2.449.0-1816181509_4arch_7dpi_4feat_6f8d1808e3179e8ff153d9ad52410688_apkmirror.com/decompiled_apktool/res"
OUTPUT_DIR = "/media/jeffer/5aab5a95-8290-d3f7-2e4f-8c27cc2d09a93/CASOSEX/docs/spec"

def extract_lottie_assets(res_dir):
    lottie_files = []
    raw_dir = os.path.join(res_dir, "raw")
    if os.path.exists(raw_dir):
        for f in os.listdir(raw_dir):
            if f.endswith(".json"):
                full_path = os.path.join(raw_dir, f)
                try:
                    with open(full_path, "r", encoding="utf-8") as fp:
                        data = json.load(fp)
                        if "v" in data and "fr" in data and "layers" in data:
                            lottie_files.append({
                                "name": f,
                                "size_bytes": os.path.getsize(full_path),
                                "layers_count": len(data.get("layers", []))
                            })
                except Exception:
                    pass
    return lottie_files

def extract_color_tokens(res_dir):
    colors = {}
    values_dir = os.path.join(res_dir, "values")
    if os.path.exists(values_dir):
        for f in os.listdir(values_dir):
            if "color" in f and f.endswith(".xml"):
                full_path = os.path.join(values_dir, f)
                try:
                    with open(full_path, "r", encoding="utf-8") as fp:
                        content = fp.read()
                        matches = re.findall(r'<color name="([^"]+)">([^<]+)</color>', content)
                        for name, val in matches:
                            colors[name] = val.strip()
                except Exception:
                    pass
    return colors

def main():
    print(f"🔍 Inspecting Mercado Pago APK resources at: {MP_RES_DIR}")
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    lottie_assets = extract_lottie_assets(MP_RES_DIR)
    colors = extract_color_tokens(MP_RES_DIR)
    
    dna_spec = {
        "metadata": {
            "title": "Mercado Pago Mobile AppShell DNA Tokens Specification",
            "version": "1.0.0",
            "extracted_at": "2026-08-26",
            "target": "CASOSEX Volúpia Cockpit V8 (mode:mobile-app-first)"
        },
        "mobile_app_first_patterns": {
            "top_actions": {
                "min_height_px": 48,
                "padding": "12px 16px",
                "components": ["ProfileAvatar", "PrivacyToggle (Hide/Show Balance)", "NotificationBell", "QuickHelp"]
            },
            "bottom_glass_dock": {
                "min_height_px": 64,
                "touch_target_min_px": 44,
                "safe_area_bottom_inset": "env(safe-area-inset-bottom, 16px)",
                "backdrop_blur": "blur(16px)",
                "border_gradient": "linear-gradient(90deg, rgba(225,29,72,0.3), rgba(140,87,255,0.3))"
            },
            "carousel_snap": {
                "alignment": "snap-x mandatory",
                "card_min_width_px": 280,
                "gap_px": 12,
                "scroll_behavior": "smooth"
            },
            "bottom_sheet_layer": {
                "border_radius": "24px 24px 0 0",
                "drag_handle_width_px": 36,
                "drag_handle_height_px": 4,
                "animation": "slide-up 0.3s cubic-bezier(0.16, 1, 0.3, 1)"
            }
        },
        "extracted_stats": {
            "lottie_micro_animations_count": len(lottie_assets),
            "sample_lotties": lottie_assets[:10],
            "total_color_tokens": len(colors),
            "sample_colors": {k: colors[k] for k in list(colors.keys())[:15]}
        },
        "casosex_volupia_mapped_tokens": {
            "background": "#0c0a0b",
            "surface_card": "#161214",
            "glass_dock": "rgba(22, 18, 20, 0.85)",
            "brand_accent_rose": "#e11d48",
            "brand_accent_violet": "#8C57FF",
            "text_primary": "#faf7f5",
            "text_secondary": "#a39b94"
        }
    }
    
    json_path = os.path.join(OUTPUT_DIR, "mobile-app-first-dna-tokens.json")
    with open(json_path, "w", encoding="utf-8") as fp:
        json.dump(dna_spec, fp, indent=2, ensure_ascii=False)
    print(f"✅ Generated JSON DNA tokens: {json_path}")
    
    yaml_lines = [
        "# Mercado Pago Mobile AppShell DNA Tokens Specification",
        "# Auto-generated by tools/adsentice_mp_mobile_dna_extractor.py",
        "metadata:",
        "  title: Mercado Pago Mobile AppShell DNA Tokens",
        "  version: 1.0.0",
        "  target: CASOSEX Volúpia Cockpit V8 (mode:mobile-app-first)",
        "mobile_app_first_patterns:",
        "  top_actions:",
        "    min_height_px: 48",
        "    components: [ProfileAvatar, PrivacyToggle, NotificationBell]",
        "  bottom_glass_dock:",
        "    min_height_px: 64",
        "    touch_target_min_px: 44",
        "    backdrop_blur: 'blur(16px)'",
        "  carousel_snap:",
        "    alignment: 'snap-x mandatory'",
        "    card_min_width_px: 280",
        "  bottom_sheet_layer:",
        "    border_radius: '24px 24px 0 0'",
        "extracted_stats:",
         f"  lottie_count: {len(lottie_assets)}",
         f"  color_tokens_count: {len(colors)}",
        "casosex_volupia_mapped_tokens:",
        "  background: '#0c0a0b'",
        "  surface_card: '#161214'",
        "  brand_accent_rose: '#e11d48'",
        "  brand_accent_violet: '#8C57FF'"
    ]
    yaml_path = os.path.join(OUTPUT_DIR, "mobile-app-first-dna-tokens.yaml")
    with open(yaml_path, "w", encoding="utf-8") as fp:
        fp.write("\n".join(yaml_lines) + "\n")
    print(f"✅ Generated YAML DNA tokens: {yaml_path}")

if __name__ == "__main__":
    main()
